name: Build Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        - name: macOS
          os: macos-latest

    name: Build for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod-${{ matrix.config.name }}
          path: |
            ${{ github.workspace }}/**/*.geode
